apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: channel-carrier-allchannel
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: channel-carrier-allchannel
  chart:
    git: https://github.com/alvaropicazo/blockchain-automation-framework.git
    ref: demo-testing
    path: platforms/hyperledger-fabric/charts/create_channel   
  values:
    metadata:
      namespace: carrier-net
      network:
        version 2.2.2
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.dev2.aws.blockchaincloudpoc-develop.com:20002
      authpath: demo-testcarrier-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/carrier-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/carrier-net/orderer 
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel
    orderer:
      address: orderer60.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
    channeltx: |-
      Cv0DChgKFggCGgYI0JulhAYiCmFsbGNoYW5uZWwS4AMK3QMKCmFsbGNoYW5uZWwSWBJGCgtBcHBs
      aWNhdGlvbhI3EhAKDHdhcmVob3VzZU1TUBIAEg4KCmNhcnJpZXJNU1ASABITCg9tYW51ZmFjdHVy
      ZXJNU1ASABoOCgpDb25zb3J0aXVtEgAa9AISyAIKC0FwcGxpY2F0aW9uErgCCAESDgoKY2Fycmll
      ck1TUBIAEhMKD21hbnVmYWN0dXJlck1TUBIAEhAKDHdhcmVob3VzZU1TUBIAGiQKDENhcGFiaWxp
      dGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZB
      ZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggD
      EgoKBkFkbWlucxACGgZBZG1pbnMiLAoLRW5kb3JzZW1lbnQSHRITCAMSDwoLRW5kb3JzZW1lbnQQ
      AhoGQWRtaW5zIjUKFExpZmVjeWNsZUVuZG9yc2VtZW50Eh0SEwgDEg8KC0VuZG9yc2VtZW50EAIa
      BkFkbWlucyoGQWRtaW5zGicKCkNvbnNvcnRpdW0SGRIXChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0=