apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-channelcheck-malv
  namespace: malv-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-channelcheck-malv
  chart:
    git: https://github.com/alvaropicazo/blockchain-automation-framework.git
    ref: addchannel-issue
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: malv-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.malv-net.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
      localmspid: malvMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: malv-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/malv-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/malv-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: channelcheck      
    orderer:
      address: orderer60.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
    anchorstx: |-
      Ct4CChoKGAgCGgYIw4K5gQYiDGNoYW5uZWxjaGVjaxK/Agq8AgoMY2hhbm5lbGNoZWNrEmASXgoL
      QXBwbGljYXRpb24STwgBEksKB21hbHZNU1ASQBoHCgNNU1ASACILCgdSZWFkZXJzEgAiCwoHV3Jp
      dGVycxIAIgoKBkFkbWlucxIAIg8KC0VuZG9yc2VtZW50EgAayQESxgEKC0FwcGxpY2F0aW9uErYB
      CAESsQEKB21hbHZNU1ASpQEIARoHCgNNU1ASABpZCgtBbmNob3JQZWVycxJKEkAKPgo5cGVlcjAu
      bWFsdi1uZXQuaGYuZGV2Mi5hd3MuYmxvY2tjaGFpbmNsb3VkcG9jLWRldmVsb3AuY29tEPtBGgZB
      ZG1pbnMiCgoGQWRtaW5zEgAiDwoLRW5kb3JzZW1lbnQSACILCgdSZWFkZXJzEgAiCwoHV3JpdGVy
      cxIAKgZBZG1pbnM=

