apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-allchannel-malv
  namespace: malv-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-allchannel-malv
  chart:
    git: https://github.com/alvaropicazo/blockchain-automation-framework.git
    ref: marketplace
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: malv-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.malv-net.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
      localmspid: malvMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: devmalv-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/malv-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/malv-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer60.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
    anchorstx: |-
      CtoCChgKFggCGgYIxe32hgYiCmFsbGNoYW5uZWwSvQIKugIKCmFsbGNoYW5uZWwSYBJeCgtBcHBs
      aWNhdGlvbhJPCAESSwoHbWFsdk1TUBJAGgcKA01TUBIAIgsKB1dyaXRlcnMSACIKCgZBZG1pbnMS
      ACIPCgtFbmRvcnNlbWVudBIAIgsKB1JlYWRlcnMSABrJARLGAQoLQXBwbGljYXRpb24StgEIARKx
      AQoHbWFsdk1TUBKlAQgBGlkKC0FuY2hvclBlZXJzEkoSQAo+CjlwZWVyMC5tYWx2LW5ldC5oZi5k
      ZXYyLmF3cy5ibG9ja2NoYWluY2xvdWRwb2MtZGV2ZWxvcC5jb20Q+0EaBkFkbWlucxoHCgNNU1AS
      ACIPCgtFbmRvcnNlbWVudBIAIgsKB1JlYWRlcnMSACILCgdXcml0ZXJzEgAiCgoGQWRtaW5zEgAq
      BkFkbWlucw==

