apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: channel-salvaro-allchannel
  namespace: salvaro-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: osn-channel-salvaro-allchannel
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-fabric-alvaro
        namespace: flux-fabric-alvaro
      chart: platforms/hyperledger-fabric/charts/fabric-osnadmin-channel-create   
  values:
    metadata:
      namespace: salvaro-net
      network:
        version: 2.5.4
      images:
        fabrictools: ghcr.io/hyperledger/bevel-fabric-tools:2.5.4
        alpineutils: ghcr.io/hyperledger/bevel-alpine:latest

    vault:
      role: vault-role
      address: http://98.64.226.131:20001
      authpath: fabric-alvarosalvaro
      adminsecretprefix: secretsv2/data/salvaro/ordererOrganizations/salvaro-net/users/admin
      orderersecretprefix: secretsv2/data/salvaro/ordererOrganizations/salvaro-net/orderers 
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: regcred
    
    channel:
      name: allchannel
    orderers:
      orderer_info: orderer5*orderer6*
    add_orderer: true

    orderer:
      name: orderer5
      localmspid: salvaroMSP
      address: orderer5.hlf.blockchaincloudpoc-develop.com:443
