apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: salvaro-cacerts-job
  namespace: salvaro-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: salvaro-cacerts-job
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-fabric-alvaro
        namespace: flux-fabric-alvaro
      chart: platforms/hyperledger-fabric/charts/fabric-cacerts-gen
  values:
    metadata:
      name: salvaro
      component_name: salvaro-net
      namespace: salvaro-net    
      images:
       alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
    vault:
      role: vault-role
      address: http://98.64.226.131:20001
      authpath: fabric-alvarosalvaro
      secretcryptoprefix: secretsv2/data/salvaro/ordererOrganizations/salvaro-net/ca
      secretcredentialsprefix: secretsv2/data/salvaro/credentials/salvaro-net/ca/salvaro
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: regcred
      
    ca:
      subject: /C=GB/ST=London/L=London/O=Orderer/CN=ca.salvaro-net
