apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: caalvcaalvquorum
  namespace: caalv-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: caalvcaalvquorum
  helmVersion: v3
  chart:
    git: https://github.com/alvaropicazo/blockchain-automation-framework.git
    ref: feat1551-tesversion
    path: platforms/quorum/charts/node_quorum_member
  values:
    replicaCount: 1
    metadata:
      namespace: caalv-quo
      labels:
    images:
      node: quorumengineering/quorum:21.4.1
      alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      tessera: quorumengineering/tessera:21.7.2
      busybox: busybox
      mysql: mysql/mysql-server:5.7
    node:
      name: caalv
      status: default
      consensus: ibft
      subject: O=Carrier,OU=Carrier,L=51.50/-0.13/London,C=GB
      mountPath: /etc/quorum/qdata
      imagePullSecret: regcred
      keystore: keystore_1
      
      servicetype: ClusterIP
      lock: false
      ports:
        rpc: 8546
        raft: 50401
        tm: 443
        quorum: 21000
        db: 3306
      dbname: demodb
      mysqluser: demouser
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secretsv2/data/caalv-quo/crypto/caalv
      serviceaccountname: vault-auth
      keyname: quorum
      tm_keyname: transaction
      role: vault-role
      authpath: quorumcaalv
    tessera:
      dburl: "jdbc:mysql://caalv-tessera:3306/demodb"
      dbusername: demouser
      url: "https://caalv-tm.quo.dev2.aws.blockchaincloudpoc-develop.com:443"
      clienturl: "http://caalv-tessera:8888" #TODO: Enable tls strict for q2t
      othernodes:
        - url: https://caalv-tm.quo.dev2.aws.blockchaincloudpoc-develop.com
        - url: https://stoalv-tm.quo.dev2.aws.blockchaincloudpoc-develop.com
      tls: "STRICT"
      trust: "TOFU"
    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDEwLAogICAgImhvbWVzdGVhZEJsb2NrIjogMCwKICAgICJlaXAxNTBCbG9jayI6IDAsCiAgICAiZWlwMTUwSGFzaCI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICAgImVpcDE1NUJsb2NrIjogMCwKICAgICJlaXAxNThCbG9jayI6IDAsCiAgICAiYnl6YW50aXVtQmxvY2siOiAwLAogICAgImNvbnN0YW50aW5vcGxlQmxvY2siOiAwLAogICAgInBldGVyc2J1cmdCbG9jayI6IDAsCiAgICAiaXN0YW5idWxCbG9jayI6IDAsCiAgICAiaXN0YW5idWwiOiB7CiAgICAgICJlcG9jaCI6IDMwMDAwLAogICAgICAicG9saWN5IjogMCwKICAgICAgImNlaWwyTmJ5M0Jsb2NrIjogMAogICAgfSwKICAgICJ0eG5TaXplTGltaXQiOiAxMjgsCiAgICAicWlwNzE0QmxvY2siOiAwLAogICAgImlzTVBTIjogZmFsc2UsCiAgICAiaXNRdW9ydW0iOiB0cnVlLAogICAgIm1heENvZGVTaXplQ29uZmlnIjogWwogICAgICB7CiAgICAgICAgImJsb2NrIjogMCwKICAgICAgICAic2l6ZSI6IDEyOAogICAgICB9CiAgICBdCiAgfSwKICAibm9uY2UiOiAiMHgwIiwKICAidGltZXN0YW1wIjogIjB4NjE3YTc2YTAiLAogICJleHRyYURhdGEiOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwZjg5YWY4NTQ5NGRjMmIxMzVjNzIyYTMwZTMyMTQzNTkxYWRhMmVlNjBjNjcxZGIyMmQ5NDdjYzM5ZGE1ZWYzOTJiYTkxYWRjYzYyNzQ1YmU1NWYwNDg2ODdhYTQ5NDk5NDk5YWY1ZTQ0YWIxMWJmNDdjMTRhNzBiOGRmNjE5ZjU5NDQyYTI5NDZlZGMzNGQ0NzcwZDA3ODIwZGNkZGVlOTM5OTQ5ZTk1YzdmMzhhYzViODQxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGMwIiwKICAiZ2FzTGltaXQiOiAiMHhlMDAwMDAwMCIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAibWl4SGFzaCI6ICIweDYzNzQ2OTYzNjE2YzIwNjI3OTdhNjE2ZTc0Njk2ZTY1MjA2NjYxNzU2Yzc0MjA3NDZmNmM2NTcyNjE2ZTYzNjUiLAogICJjb2luYmFzZSI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICJhbGxvYyI6IHsKICAgICI2ZWRjMzRkNDc3MGQwNzgyMGRjZGRlZTkzOTk0OWU5NWM3ZjM4YWM1IjogewogICAgICAiYmFsYW5jZSI6ICIweDQ0NmMzYjE1Zjk5MjY2ODdkMmM0MDUzNGZkYjU2NDAwMDAwMDAwMDAwMCIKICAgIH0sCiAgICAiN2NjMzlkYTVlZjM5MmJhOTFhZGNjNjI3NDViZTU1ZjA0ODY4N2FhNCI6IHsKICAgICAgImJhbGFuY2UiOiAiMHg0NDZjM2IxNWY5OTI2Njg3ZDJjNDA1MzRmZGI1NjQwMDAwMDAwMDAwMDAiCiAgICB9LAogICAgIjk5NDk5YWY1ZTQ0YWIxMWJmNDdjMTRhNzBiOGRmNjE5ZjU5NDQyYTIiOiB7CiAgICAgICJiYWxhbmNlIjogIjB4NDQ2YzNiMTVmOTkyNjY4N2QyYzQwNTM0ZmRiNTY0MDAwMDAwMDAwMDAwIgogICAgfSwKICAgICJkYzJiMTM1YzcyMmEzMGUzMjE0MzU5MWFkYTJlZTYwYzY3MWRiMjJkIjogewogICAgICAiYmFsYW5jZSI6ICIweDQ0NmMzYjE1Zjk5MjY2ODdkMmM0MDUzNGZkYjU2NDAwMDAwMDAwMDAwMCIKICAgIH0KICB9LAogICJudW1iZXIiOiAiMHgwIiwKICAiZ2FzVXNlZCI6ICIweDAiLAogICJwYXJlbnRIYXNoIjogIjB4MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIKfQ==
    staticnodes: 
      [
    "enode://94bdf00405ee1346c0de72619c750c7e7260342dae9d4c96f6054b4cabc151446b3089168f3bbcc518e2b5bf4232cbcb26b5b4dd7f773927ae7fea8b2a00a089@sucalv1.quo.dev2.aws.blockchaincloudpoc-develop.com:15010?discport=0",
    "enode://229447d0f748a8b6643b5421e3681b73e9fa28075f576fc96a4c78c9a96da70e16ab596877d66fa0b7737dcc334ce912be1a6e46a8f3d5f5c842e05e05c3664b@sucalv2.quo.dev2.aws.blockchaincloudpoc-develop.com:15012?discport=0",
    "enode://612d9015120bb0dfc64b34d1db5a97e6bf76fcb991c2f91d8028be1fd3d52cfaca37e28ef9f495b64b484d0a091ba6da4a88890217a6574c3bae1e38e55517ef@sucalv3.quo.dev2.aws.blockchaincloudpoc-develop.com:15014?discport=0",
    "enode://7b2103f12f547799226117547ce13d53d63f4edea576e2420eb30501dd2bdd01f5fecdd8717b21a5077c786793d5d2b82ccec97bf1558ef7c1ca7dabf737e2d8@sucalv4.quo.dev2.aws.blockchaincloudpoc-develop.com:15016?discport=0",
    "enode://a7e6fd4e98b16d3080e780d929509de7ac44ebbd9a6b67c245548549b4671a7b16f9596427659f75ff53aee5542b88e003523de59db0e6a9150af5e4da31c786@caalv.quo.dev2.aws.blockchaincloudpoc-develop.com:15018?discport=0",
    "enode://568b2d392c8d4118e8e096b4fa7624e12c0f7154b7dd9ce042e6c06ef2a21230d8df7913191e8092083a8f752292053977673639e3f27f77997833ea62dd11b6@stoalv.quo.dev2.aws.blockchaincloudpoc-develop.com:15020?discport=0"
]
    proxy:
      provider: "ambassador"
      external_url: caalv.quo.dev2.aws.blockchaincloudpoc-develop.com
      portTM: 443
      rpcport: 15019
      quorumport: 15018
    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi
      dbstorage: 1Gi
