apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: malv
  namespace: malv-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: malv
  interval: 1m
  chart:
   spec:
    chart: platforms/quorum/charts/quorum-node
    sourceRef:
      kind: GitRepository
      name: flux-alv
      namespace: flux-alv
  values:
    global:
      serviceAccountName: vault-auth
      cluster:
        provider: azure
        cloudNativeServices: false
      vault:
        type: hashicorp
        network: quorum
        address: http://98.64.226.131:20001
        secretPrefix: "data/alvmalv"
        secretEngine: secretsv2
        role: vault-role
        authPath: alvmalv
      proxy:
        provider: ambassador
        externalUrlSuffix: malv.quo.blockchaincloudpoc-develop.com
        p2p: 15066
        tmport: 443
    storage:
      size: "2Gi"
    tessera:
      enabled: true
      tessera:
        port:
        resources:
          cpuLimit: 0.25
          cpuRequest: 0.05
          memLimit: "2G"
          memRequest: "1G"
        password: 'password'
      storage:
        enabled: false
        size: 1Gi
        dbSize: 2Gi
        allowedTopologies:
          enabled: false
          
    tls:
      enabled: true
      image:
        pullSecret: regcred
      settings:
        certSubject: 'CN=DLT Root CA,OU=DLT,O=DLT,L=London,C=GB'
        tmTls: strict


    node:
      goquorum:
        metrics:
          serviceMonitorEnabled: true
        resources:
          cpuLimit: 0.25
          cpuRequest: 0.05
          memLimit: "1G"
          memRequest: "300M"
        account:
          password: 'password'
        p2p:
          discovery: false
