apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: joinchannel-peer1-join-allchannel-manufacturer-peer1
  namespace: manufacturer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: joinchannel-peer1-join-allchannel-manufacturer-peer1
  chart:
    git: https://github.com/alvaropicazo/blockchain-automation-framework.git
    ref: demo-testing
    path: platforms/hyperledger-fabric/charts/join_channel
  values:
    metadata:
      namespace: manufacturer-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer1
      address: peer1.manufacturer-net.hf.demo.aws.blockchaincloudpoc-develop.com:8443
      localmspid: manufacturerMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.dev2.aws.blockchaincloudpoc-develop.com:20002
      authpath: demo-test2manufacturer-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/manufacturer-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/manufacturer-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer60.hf.dev2.aws.blockchaincloudpoc-develop.com:8443

