apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: waalv1
  namespace: waalv-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: waalv1
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/besu-node
    sourceRef:
      kind: GitRepository
      name: flux-bes-alv
      namespace: flux-bes-alv
  values:
    global:
      serviceAccountName: vault-auth
      cluster:
        provider: aws
        cloudNativeServices: false
      vault:
        type: hashicorp
        network: besu
        address: http://vault.besu.dev.aws.blockchaincloudpoc-develop.com:15020
        authPath: bes-alvwaalv
        secretEngine: secretsv2
        secretPrefix: "data/bes-alvwaalv"
        role: vault-role
      proxy:
        provider: ambassador
        externalUrlSuffix: besu.dev.aws.blockchaincloudpoc-develop.com
        p2p: 15074
        tmport: 443
    storage:
      size: "2Gi"
    tessera:
      enabled: true
      storage:
        enabled: false
        size: 1Gi
        dbSize: 2Gi
        allowedTopologies:
          enabled: false
      image:  
        tessera: 
          repository: quorumengineering/tessera
          tag: 21.7.3
        mysql: 
          repository: mysql/mysql-server
          tag: 5.7
        pullSecret: regcred
      tessera:
        removeKeysOnDelete: true
        peerNodes: 
          - url: https://caalv.besu.dev.aws.blockchaincloudpoc-develop.com
        resources:
          cpuLimit: 0.25
          cpuRequest: 0.05
          memLimit: "2G"
          memRequest: "1G"
        password: 'password'
        port: 443
        tpport: 9080
        q2tport: 8888
        metrics:
          enabled: False
          port: 9545
          serviceMonitorEnabled: False
        tlsMode: "STRICT"
        trust: "TOFU"
    tls:
      enabled: true
      image:
        pullSecret: regcred
      settings:
        certSubject: 'CN=DLT Root CA,OU=DLT,O=DLT,L=London,C=GB'
        tmTls: True
    image:
      pullSecret: regcred
      besu:
        repository: hyperledger/besu
        tag: 22.10.2
    node:
      removeKeysOnDelete: false
      isBootnode: false
      usesBootnodes: false
      besu:
        identity: O=Manufacturer,OU=Manufacturer,L=47.38/8.54/Zurich,C=CH
        envBesuOpts: ""
        resources:
          cpuLimit: 0.25
          cpuRequest: 0.05
          memLimit: "1G"
          memRequest: "300M"
        account:
          password: 12345
        p2p:
          port: 30303
          discovery: false
        rpc:
          port: 8545
        ws:
          port: 8546
        metrics:
          enabled: False
          port: 9545
          serviceMonitorEnabled: False
        privacy:
          clientport: 8888
        permissions:
          enabled: False #Add other permissioning params below this
    labels:
      service:
        - component: besu
      pvc:
      deployment:
        - owner: bevel
        - component: besu
