#helm install carrier-ca -f values/noproxy-and-novault/ca-server.yaml -n carrier-net fabric-ca-server
global:
  serviceAccountName: vault-auth
  cluster:
    provider: aws
    cloudNativeServices: false
  vault:
    type: kubernetes
  proxy:
    provider: none
    externalUrlSuffix: calvaro-net
storage:
  size: 512Mi
server:
  removeCertsOnDelete: true
  tlsStatus: true
  adminUsername: calvaro-admin
  adminPassword: calvaro-adminpw
  subject: "/C=GB/ST=London/L=London/O=Carrier"
