#helm install orderer1 -f values/noproxy-and-novault/orderer.yaml -n supplychain-net fabric-orderernode
global:
  version: 2.5.4
  serviceAccountName: vault-auth
  vault:
    type: kubernetes

  cluster:
    provider: aws
    cloudNativeServices: false
  
  proxy:
    provider: none
    externalUrlSuffix: hlf.blockchaincloudpoc-develop.com

certs:
  generateCertificates: true
  orgData:
    caAddress: ca.salvaro-net:7054
    caAdminUser: salvaro-admin
    caAdminPassword: salvaro-adminpw
    orgName: salvaro
    type: orderer
    componentSubject: "O=Orderer,L=51.50/-0.13/London,C=GB"
  settings:
    #Flag to create configmaps for the organization. This flag must be set to true when installing the first orderer/peer in organization and false for others.
    createConfigMaps: true
    refreshCertValue: false
    addPeerValue: false
    removeCertsOnDelete: true
    removeOrdererTlsOnDelete: true

orderer:
  consensus: raft
  logLevel: info
  localMspId: salvaroMSP
  tlsstatus: true
