global:
  version: 2.2.2
  serviceAccountName: vault-auth
  cluster:
    provider: aws
    cloudNativeServices: false
  vault:
    type: hashicorp
    role: vault-role
    address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:20002
    authPath: carrier
    secretEngine: secretsv2
    secretPrefix: "data/carrier"
    tls: false
  proxy:
    provider: haproxy
    externalUrlSuffix: hlf.blockchaincloudpoc-develop.com

peer:
  name: peer0
  type: anchor
  address: peer0.carrier-net.hlf.blockchaincloudpoc-develop.com:443
  localMspId: carrierMSP
  logLevel: info
  tlsStatus: true
  channelName: AllChannel
  ordererAddress: orderer1.supplychain-net.hlf.blockchaincloudpoc-develop.com:443
