#helm install ca-certs -f values/proxy-and-vault/genesis.yaml -n supplychain-net fabric-genesis
global:
  version: 2.2.2
  serviceAccountName: vault-auth
  cluster:
    provider: aws
    cloudNativeServices: false
  vault:
    type: hashicorp
    role: vault-role
    address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:20002
    authPath: supplychain
    secretEngine: secretsv2
    secretPrefix: "data/supplychain"
    tls: false
  proxy:
    provider: haproxy
    externalUrlSuffix: hlf.blockchaincloudpoc-develop.com

organizations:
  - name: supplychain
    orderers:
      - name: orderer1
        ordererAddress: orderer1.supplychain-net.hlf.blockchaincloudpoc-develop.com:443
      - name: orderer2
        ordererAddress: orderer2.supplychain-net.hlf.blockchaincloudpoc-develop.com:443
      - name: orderer3
        ordererAddress: orderer3.supplychain-net.hlf.blockchaincloudpoc-develop.com:443
    peers:
      - name: peer0
        peerAddress: peer0.supplychain-net.hlf.blockchaincloudpoc-develop.com:443 # Internal/External URI of the peer
      - name: peer1
        peerAddress: peer1.supplychain-net.hlf.blockchaincloudpoc-develop.com:443

  - name: carrier 
    peers:
    - name: peer0
      peerAddress: peer0.carrier-net.hlf.blockchaincloudpoc-develop.com:443 # External URI of the peer
consensus: raft
channels:
  - name: allchannel
    consortium: SupplyChainConsortium
    orderers:
      - supplychain  
    participants:
      - supplychain
      - carrier

settings:
  removeConfigMapOnDelete: true
