global:
  version: 2.5.4
  serviceAccountName: vault-auth
  cluster:
    provider: aws
    cloudNativeServices: false
  vault:
    type: hashicorp
    role: vault-role
    address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:20002
    authPath: calvaro
    secretEngine: secretsv2
    secretPrefix: "data/calvaro"
    tls: false

peer:
  name: peer0
  type: anchor
  address: peer0.calvaro-net.hlf.blockchaincloudpoc-develop.com:443
  localMspId: calvaroMSP
  logLevel: info
  tlsStatus: true
  channelName: allchannel
  ordererAddress: orderer11.salvaro-net.hlf.blockchaincloudpoc-develop.com:443
