global:
  version: 2.5.4
  serviceAccountName: vault-auth
  cluster:
    provider: aws
    cloudNativeServices: false
  vault:
    type: hashicorp
    role: vault-role
    address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:20002
    authPath: salvaro
    secretEngine: secretsv2
    secretPrefix: "data/salvaro"
    tls: false
  proxy:
    provider: haproxy
    externalUrlSuffix: hlf.blockchaincloudpoc-develop.com
orderers:
  - name: orderer22
    adminAddress: orderer22.salvaro-net:7055 # Internal URI of the orderer ONS Admin service

orderer:
  addOrderer: true
  name: orderer22
  localMspId: salvaroMSP
  ordererAddress: orderer11.salvaro-net.hlf.blockchaincloudpoc-develop.com:443