#helm install pee0 -f values/proxy-and-vault/orderer.yaml -n carrier-net fabric-orderernode
global:
  version: 2.2.2
  serviceAccountName: vault-auth
  cluster:
    provider: aws
    cloudNativeServices: false
  vault:
    type: hashicorp
    role: vault-role
    address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:20002
    authPath: supplychain
    secretEngine: secretsv2
    secretPrefix: "data/supplychain"
    tls: false
  proxy:
    provider: haproxy
    externalUrlSuffix: hlf.blockchaincloudpoc-develop.com

certs:
  generateCertificates: true
  orgData:
    caAddress: ca.supplychain-net:7054
    caAdminUser: supplychain-admin
    caAdminPassword: supplychain-adminpw
    orgName: supplychain
    type: peer
    componentSubject: "O=Orderer,L=51.50/-0.13/London,C=GB"
  users: 
    usersList:
      - user:
        identity: user1
        attributes:
        - key: "hf.Revoker"
          value: "true"
  settings:
    #Flag to create configmaps for the organization. This flag must be set to true when installing the first orderer/peer in organization and false for others.
    createConfigMaps: false
    refreshCertValue: false
    addPeerValue: false
    removeCertsOnDelete: true
    removeOrdererTlsOnDelete: true

peer:
  gossipPeerAddress: peer1.supplychain-net.hlf.blockchaincloudpoc-develop.com:443
  logLevel: info
  localMspId: supplychainMSP
  tlsStatus: true
  cliEnabled: false
  ordererAddress: orderer1.supplychain-net.hlf.blockchaincloudpoc-develop.com:443
  builder: hyperledger/fabric-ccenv
  couchdb:
    username: supplychain-user
    password: supplychain-userpw
  upgrade: false
