#helm install pee0 -f values/proxy-and-vault/orderer.yaml -n carrier-net fabric-orderernode
global:
  version: 2.5.4
  serviceAccountName: vault-auth
  cluster:
    provider: aws
    cloudNativeServices: false
  vault:
    type: hashicorp
    role: vault-role
    address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:20002
    authPath: calvaro
    secretEngine: secretsv2
    secretPrefix: "data/calvaro"
    tls: false
  proxy:
    provider: haproxy
    externalUrlSuffix: hlf.blockchaincloudpoc-develop.com

certs:
  generateCertificates: true
  orgData:
    caAddress: ca.calvaro-net:7054
    caAdminUser: calvaro-admin
    caAdminPassword: calvaro-adminpw
    orgName: calvaro
    type: peer
    componentSubject: "O=Orderer,L=51.50/-0.13/London,C=GB"
  users: 
    usersList:
      - user:
        identity: user1
        attributes:
        - key: "hf.Revoker"
          value: "true"
  settings:
    #Flag to create configmaps for the organization. This flag must be set to true when installing the first orderer/peer in organization and false for others.
    createConfigMaps: false
    refreshCertValue: false
    addPeerValue: false
    removeCertsOnDelete: true
    removeOrdererTlsOnDelete: true

peer:
  gossipPeerAddress: peer0.calvaro-net.hlf.blockchaincloudpoc-develop.com
  logLevel: info
  localMspId: calvaroMSP
  tlsStatus: true
  cliEnabled: false
  ordererAddress: orderer11.salvaro-net.hlf.blockchaincloudpoc-develop.com
  builder: hyperledger/fabric-ccenv
  couchdb:
    username: calvaro-user
    password: calvaro-userpw
  upgrade: false
