
global:
  version: 2.2.2
  serviceAccountName: vault-auth
  cluster:
    provider: aws
    cloudNativeServices: false
  vault:
    type: hashicorp
    role: vault-role
    address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:20002
    authPath: supplychain
    secretEngine: secretsv2
    secretPrefix: "data/supplychain"
    tls: false

peerName: peer0
localMspId: supplychainMSP
tlsStatus: true
ordererAddress: orderer1.supplychain-net.hlf.blockchaincloudpoc-develop.com:443
channelName: allchannel

organization:
  name: warehouse
  peers:
    - name: peer0
      type: anchor
      peerAddress: peer0.warehouse-net.hlf.blockchaincloudpoc-develop.com:443

existingParticipants:
  - name: carrier 
    peerName: peer0

