#helm install pee0-warehouse -f values/noproxy-and-novault/peer.yaml -n warehouse-net fabric-peer
global:
  version: 2.2.2
  serviceAccountName: vault-auth
  cluster:
    provider: aws
    cloudNativeServices: false
  vault:
    type: hashicorp
    role: vault-role
    address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:20002
    authPath: warehouse
    secretEngine: secretsv2
    secretPrefix: "data/warehouse"
    tls: false
  proxy:
    provider: haproxy
    externalUrlSuffix: hlf.blockchaincloudpoc-develop.com

certs:
  generateCertificates: true
  orgData:
    caAddress: ca.warehouse-net.hlf.blockchaincloudpoc-develop.com
    caAdminUser: warehouse-admin
    caAdminPassword: warehouse-adminpw
    orgName: warehouse
    type: peer
    componentSubject: "O=Warehouse,OU=Warehouse,L=42.36/-71.06/Boston,C=US"
  users: 
    usersList:
      - user:
        identity: user1
        attributes:
        - key: "hf.Revoker"
          value: "true"
  settings:
    #Flag to create configmaps for the organization. This flag must be set to true when installing the first orderer/peer in organization and false for others.
    createConfigMaps: true
    refreshCertValue: false
    addPeerValue: false
    removeCertsOnDelete: true
    removeOrdererTlsOnDelete: true
storage:
  enabled: false
peer:
  gossipPeerAddress: 
  logLevel: info
  localMspId: warehouseMSP
  tlsStatus: true
  cliEnabled: true
  ordererAddress: orderer1.supplychain-net.hlf.blockchaincloudpoc-develop.com:443
  builder: hyperledger/fabric-ccenv
  couchdb:
    username: warehouse-user
    password: warehouse-userpw
  upgrade: false
