apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: salv-tessera-job
  namespace: salv-quo
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: salv-tessera-job
  chart:
    path: platforms/quorum/charts/tessera_key_mgmt
    git: https://github.com/alvaropicazo/blockchain-automation-framework.git
    ref: testquorum
  values:
    metadata:
      name: salv-tessera-job
      namespace: salv-quo    
    image:      
      repository: quorumengineering/tessera:21.4.0
      pullSecret: regcred
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: quorumsalv
      role: vault-role
      serviceaccountname: vault-auth
      tmprefix: secret/salv-quo/crypto/salv/transaction
