apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: peer1-manufacturer-cli
  namespace: manufacturer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: peer1-manufacturer-cli
  chart:
    git: https://github.com/alvaropicazo/blockchain-automation-framework.git
    ref: demo-testing
    path: platforms/hyperledger-fabric/charts/fabric_cli    
  values:
    metadata:
      namespace: manufacturer-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    storage:
      class: manufacturersc
      size: 256Mi
    vault:
      role: vault-role
      address: http://vault.dev2.aws.blockchaincloudpoc-develop.com:20002
      authpath: demo-test2manufacturer-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/manufacturer-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/manufacturer-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    peer:
      name: peer1
      localmspid: manufacturerMSP
      tlsstatus: true
      address: peer1.manufacturer-net.hf.demo.aws.blockchaincloudpoc-develop.com:8443
    orderer:
      address: orderer60.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
