apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: peer0-manufacta-cli
  namespace: manufacta-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: peer0-manufacta-cli
  chart:
    git: https://github.com/alvaropicazo/blockchain-automation-framework.git
    ref: testing-dev
    path: platforms/hyperledger-fabric/charts/fabric_cli    
  values:
    metadata:
      namespace: manufacta-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    storage:
      class: manufactasc
      size: 256Mi
    vault:
      role: vault-role
      address: http://vault.internal.demo.aws.blockchaincloudpoc.com:9001
      authpath: alvmanufacta-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/manufacta-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/manufacta-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    peer:
      name: peer0
      localmspid: manufactaMSP
      tlsstatus: true
      address: peer0.manufacta-net.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
    orderer:
      address: orderer60.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
