apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: stalv-net-ca-tools
  namespace: stalv-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: stalv-net-ca-tools
  chart:
    git: https://github.com/alvaropicazo/blockchain-automation-framework.git
    ref: marketplace
    path: platforms/hyperledger-fabric/charts/catools
  values:
    metadata:
      namespace: stalv-net
      name: ca-tools
    replicaCount: 1

    image:
      repository: hyperledger/fabric-ca-tools
      tag: 1.2.1
      pullPolicy: IfNotPresent
      
    storage:
      storageclassname: stalvsc
      storagesize: 512Mi
