apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: salvvalidator2ibft
  namespace: salv-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: salvvalidator2ibft
  chart:
    git: https://github.com/alvaropicazo/blockchain-automation-framework.git
    ref: testfeat1551check
    path: platforms/hyperledger-besu/charts/node_validator 
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://cc861a1848c728f1c29768e842c079cf4c91b663b2ad3093d18cd3a88fd05cc4f5e74ff1482e983b67d2ceaa9925c75cac130e9d1246dfb24221444ec0394caa@validator1.bes.dev2.aws.blockchaincloudpoc-develop.com:15011"
      
      - "enode://acbe19f46ead6504ecfb1bc77216e35d83d8d3135406d5a37a4c173fea1c77869a3f6e8793ec4bd328639c23a169d863dcc7ff996d54b92e84d15d398ea206cd@validator2.bes.dev2.aws.blockchaincloudpoc-develop.com:15013"
      
      - "enode://e5b6918f89c2658fe0e54048b50e41a054d9144e077be4829a99d05a14a9031945aca989fd95db78aba61f00714e2a20dea4cd74511ef8a950a241f880ff4e3e@validator3.bes.dev2.aws.blockchaincloudpoc-develop.com:15015"
      
      - "enode://e96cb11550f881b35680795361a4dbb7c2b2d161362f6b6da306da554be821b51303096d84487d944b285499cda0a1ac416fa7fe5c6e9f3134ccdc6f5f1f3758@validator4.bes.dev2.aws.blockchaincloudpoc-develop.com:15017"
      
      - "enode://d84d2c34ae666089a9e6a2881b650446e6d83912673ef0968b2fe90cfe25c2f67a0ce3af91467b021edce3a3f8c77e09f8342b4b65fcc26279f56ffc1570a320@calv.bes.dev2.aws.blockchaincloudpoc-develop.com:15010"
      
      - "enode://edd45b7ac1e746cd8eb534e280a687924556a906975ee896da044df44df07b7346dc73a44bbe644900cdfb9ff642861e1711d2b03620e17a4480e636754780db@malv.bes.dev2.aws.blockchaincloudpoc-develop.com:15013"
      

    metadata:
      namespace: salv-bes
      labels:

    ambassador:
      external_url_suffix: bes.dev2.aws.blockchaincloudpoc-develop.com

    liveliness_check:
      enabled: false
 
    proxy:
      provider: ambassador
      external_url: salv.bes.dev2.aws.blockchaincloudpoc-develop.com
      p2p: 15013
      rpc: 15014

    images:
      node: hyperledger/besu:1.5.5
      alpineutils: hyperledgerlabs/alpine-utils:1.0

    node:
      name: validator2
      tls: True
      consensus: ibft
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secretsv2/data/salv-bes/crypto/validator2
      serviceaccountname: vault-auth
      keyname: data
      tlsdir: tls
      role: vault-role
      authpath: besusalv

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NGVmMjEzMjlhZmVmZGVjZmNhZGFiMTE5NDgyMWViNWNhYjk4MWNhNzg5NGQ3ZTMxOTg0Y2E0YmU2YWQwOTE1NzA3ODMxYjc0MjQ3NTY2NTljZmQ5NGY1MzJmZmY1MTJmNjI2N2JkZmI1NjcyMjI0YmYxNWE5ZmNlNzQ2MjU5NDQ3ODE0MjhmNDFiMGZlYzU3N2NiNTI4OTI0MzhjZjhkM2JkMDVlMTA4MDg0MDAwMDAwMDBjMCIKfQ==
