apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: salvvalidator2ibft
  namespace: salv-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: salvvalidator2ibft
  chart:
    git: https://github.com/alvaropicazo/blockchain-automation-framework.git
    ref: feature-1669
    path: platforms/hyperledger-besu/charts/node_validator 
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://3c1a34f666c8cb89c3450d6b3d8e5bb68a9d304fa18879d67ab8d25ed399c836babd16013e7fc207216d64dfcf5fb3f6c8809b3b26294eb9e0530962ba76c8a4@validator1.bes.dev2.aws.blockchaincloudpoc-develop.com:15011"
      
      - "enode://89051a0e7b8a0e044c5f481f880e92dedae0d0da9707c2d2a63383f396502246563dc47369b138baa9eca7814d4cc808a35f3b3019fb017d35e10aba6909475a@validator2.bes.dev2.aws.blockchaincloudpoc-develop.com:15013"
      
      - "enode://9c2a2562db21c67aaf8d4a018b2df65138ea7f15a9117dd20df0b397c491f7446471ea98dc87f29a75bdd2049228ce293c8ef9b4ff55fb5bbad6ad26408e68e7@validator3.bes.dev2.aws.blockchaincloudpoc-develop.com:15015"
      
      - "enode://5b3a63660fbd4b941c9d1fc1198dfc6274ceb41e24655e730bb7b09409de183804ef3ce8d30d3eee20923842bdfd82966a38defb4d2899e0e4d128c10aebb69e@validator4.bes.dev2.aws.blockchaincloudpoc-develop.com:15017"
      
      - "enode://8a021c899674f137c96378f6453ff47facc293ddafc1009fb3a9f77d5a846ffa828b08b0c4e07152d9bd7048d8fffbd2b89a93641a0ff1f5b86441ebdb126060@calv.bes.dev2.aws.blockchaincloudpoc-develop.com:15010"
      
      - "enode://9ec375c020afe2fcb27b1c1c08d7d07e9ab13a3a8915ef76df4a00b610d90a42b28c4c1dd3ae269e8cc56fc8c3c491db68a7d9dfd185f9a4555d99f01629e1b3@malv.bes.dev2.aws.blockchaincloudpoc-develop.com:15013"
      

    metadata:
      namespace: salv-bes
      labels:

    ambassador:
      external_url_suffix: bes.dev2.aws.blockchaincloudpoc-develop.com

    liveliness_check:
      enabled: false
 
    proxy:
      provider: ambassador
      external_url: salv.bes.dev2.aws.blockchaincloudpoc-develop.com
      p2p: 15013
      rpc: 15014

    images:
      node: hyperledger/besu:1.5.5
      alpineutils: hyperledgerlabs/alpine-utils:1.0

    node:
      name: validator2
      tls: True
      consensus: ibft
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secret/salv-bes/crypto/validator2
      serviceaccountname: vault-auth
      keyname: data
      tlsdir: tls
      role: vault-role
      authpath: besusalv

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NDhmMTAxYTFjY2ZlMTIyNGZjZTU3NGJmMzJjMDA1ZmFjZjIwZTg4NGI5NGY1NjViY2M0NjJjMzhiOWZiNDVlZmRkNTMzOGM2NzZiZDFhZDdjYzc5NDY2YTJmNTM3ZGIxNTkzZTIwODU5ZWMyNWM4NTQwMGY1MzM5MTAzMWE5NDA0NDcyYmRiMzEwOGRlMDY2ODNlODdhODRhYWY1NTY5ZDFjODYxZTc4MDg0MDAwMDAwMDBjMCIKfQ==
