apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: peer1
  namespace: calvaro-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: peer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-fabric-alvaro
        namespace: flux-fabric-alvaro
      chart: platforms/hyperledger-fabric/charts/fabric-peernode    
  values:
    global:
      version: 2.5.4
      serviceAccountName: vault-auth
      cluster:
        provider: azure
        cloudNativeServices: false
      vault:
        type: hashicorp
        network: fabric
        address: http://98.64.226.131:20001
        authPath: fabric-alvarocalvaro
        secretEngine: secretsv2
        secretPrefix: "data/fabric-alvarocalvaro"
        role: vault-role
        tls: false
      proxy:
        provider: haproxy
        externalUrlSuffix: hlf.blockchaincloudpoc-develop.com

    storage:
      enabled: False
      peer: 512Mi
      couchdb: 512Mi
      reclaimPolicy: "Delete" 
      volumeBindingMode: Immediate 
      allowedTopologies:
        enabled: false

    certs:
      generateCertificates: true
      orgData:
        caAddress: ca.calvaro-net.hlf.blockchaincloudpoc-develop.com
        caAdminUser: calvaro-admin
        caAdminPassword: calvaro-adminpw
        orgName: calvaro
        type: peer
        componentSubject: "O=Carrier,OU=Carrier,L=51.50/-0.13/London,C=GB"

      users: 
        usersList:
        - {'user': None, 'identity': 'user1', 'attributes': [{'key': 'hf.Revoker', 'value': 'true'}]}
        - {'user': None, 'identity': 'user2', 'attributes': [{'key': 'hf.Revoker', 'value': 'true'}]}

      settings:
        createConfigMaps: True
        refreshCertValue: false
        addPeerValue: false
        removeCertsOnDelete: true
        removeOrdererTlsOnDelete: true

    image:
      couchdb: ghcr.io/hyperledger/bevel-fabric-couchdb
      peer: ghcr.io/hyperledger/bevel-fabric-peer
      alpineUtils: ghcr.io/hyperledger/bevel-alpine:latest
      pullSecret: regcred

    peer:
      gossipPeerAddress: peer1.calvaro-net.hlf.blockchaincloudpoc-develop.com:443
      logLevel: info
      localMspId: calvaroMSP
      tlsStatus: true
      cliEnabled: True
      ordererAddress: orderer7.salvaro-net.hlf.blockchaincloudpoc-develop.com:443
      builder: hyperledger/fabric-ccenv
      couchdb:
        username: calvaro-user
        password: calvaro-userpw
      mspConfig:
        organizationalUnitIdentifiers:
        nodeOUs:
          clientOUIdentifier: client
          peerOUIdentifier: peer
          adminOUIdentifier: admin
          ordererOUIdentifier: orderer
      serviceType: ClusterIP 
      loadBalancerType: ""
      ports:
        grpc:
          clusterIpPort: 7051
        events:
          clusterIpPort: 7053
        couchdb:
          clusterIpPort: 5984
        metrics:
          enabled: False
          clusterIpPort: 9443    
      resources:
        limits:
          memory: 1Gi
          cpu: 1
        requests:
          memory: 512M
          cpu: 0.25
      upgrade: False
      healthCheck: 
        retries: 20
        sleepTimeAfterError: 15

