apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-allchannel-walv
  namespace: walv-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-allchannel-walv
  chart:
    git: https://github.com/alvaropicazo/blockchain-automation-framework.git
    ref: addchannel-issue
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: walv-net
      images:
        fabrictools: hyperledger/fabric-tools:1.4.4
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.walv-net.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
      localmspid: walvMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: walv-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/walv-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/walv-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer60.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
    anchorstx: |-
      CsACChAKDggCIgphbGxjaGFubmVsEqsCCqgCCgphbGxjaGFubmVsElcSVQoLQXBwbGljYXRpb24S
      RggBEjoKB3dhbHZNU1ASLxoHCgNNU1ASACILCgdSZWFkZXJzEgAiCwoHV3JpdGVycxIAIgoKBkFk
      bWlucxIAKgZBZG1pbnMawAESvQEKC0FwcGxpY2F0aW9uEq0BCAESoAEKB3dhbHZNU1ASlAEIARoH
      CgNNU1ASABpZCgtBbmNob3JQZWVycxJKEkAKPgo5cGVlcjAud2Fsdi1uZXQuaGYuZGV2Mi5hd3Mu
      YmxvY2tjaGFpbmNsb3VkcG9jLWRldmVsb3AuY29tEPtBGgZBZG1pbnMiCwoHUmVhZGVycxIAIgsK
      B1dyaXRlcnMSACIKCgZBZG1pbnMSACoGQWRtaW5zKgZBZG1pbnM=

