apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-channelcheck-calv
  namespace: calv-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-channelcheck-calv
  chart:
    git: https://github.com/alvaropicazo/blockchain-automation-framework.git
    ref: addchannel-issue
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: calv-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.calv-net.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
      localmspid: calvMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: calv-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/calv-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/calv-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: channelcheck      
    orderer:
      address: orderer60.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
    anchorstx: |-
      Ct4CChoKGAgCGgYIwoK5gQYiDGNoYW5uZWxjaGVjaxK/Agq8AgoMY2hhbm5lbGNoZWNrEmASXgoL
      QXBwbGljYXRpb24STwgBEksKB2NhbHZNU1ASQBoHCgNNU1ASACIKCgZBZG1pbnMSACIPCgtFbmRv
      cnNlbWVudBIAIgsKB1JlYWRlcnMSACILCgdXcml0ZXJzEgAayQESxgEKC0FwcGxpY2F0aW9uErYB
      CAESsQEKB2NhbHZNU1ASpQEIARpZCgtBbmNob3JQZWVycxJKEkAKPgo5cGVlcjAuY2Fsdi1uZXQu
      aGYuZGV2Mi5hd3MuYmxvY2tjaGFpbmNsb3VkcG9jLWRldmVsb3AuY29tEPtBGgZBZG1pbnMaBwoD
      TVNQEgAiCgoGQWRtaW5zEgAiDwoLRW5kb3JzZW1lbnQSACILCgdSZWFkZXJzEgAiCwoHV3JpdGVy
      cxIAKgZBZG1pbnM=

