apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-allchannel-calv
  namespace: calv-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-allchannel-calv
  chart:
    git: https://github.com/alvaropicazo/blockchain-automation-framework.git
    ref: addchannel-issue
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: calv-net
      images:
        fabrictools: hyperledger/fabric-tools:1.4.4
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.calv-net.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
      localmspid: calvMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: calv-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/calv-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/calv-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer60.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
    anchorstx: |-
      CsACChAKDggCIgphbGxjaGFubmVsEqsCCqgCCgphbGxjaGFubmVsElcSVQoLQXBwbGljYXRpb24S
      RggBEjoKB2NhbHZNU1ASLxoHCgNNU1ASACILCgdXcml0ZXJzEgAiCgoGQWRtaW5zEgAiCwoHUmVh
      ZGVycxIAKgZBZG1pbnMawAESvQEKC0FwcGxpY2F0aW9uEq0BCAESoAEKB2NhbHZNU1ASlAEIARpZ
      CgtBbmNob3JQZWVycxJKEkAKPgo5cGVlcjAuY2Fsdi1uZXQuaGYuZGV2Mi5hd3MuYmxvY2tjaGFp
      bmNsb3VkcG9jLWRldmVsb3AuY29tEPtBGgZBZG1pbnMaBwoDTVNQEgAiCwoHUmVhZGVycxIAIgsK
      B1dyaXRlcnMSACIKCgZBZG1pbnMSACoGQWRtaW5zKgZBZG1pbnM=

