apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: stalv-tessera-job
  namespace: stalv-quo
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: stalv-tessera-job
  chart:
    path: platforms/quorum/charts/tessera_key_mgmt
    git: https://github.com/alvaropicazo/blockchain-automation-framework.git
    ref: feat1551-new
  values:
    peer:
      name: stalv  
    metadata:
      name: stalv-tessera-job
      namespace: stalv-quo    
    image:      
      repository: quorumengineering/tessera:hashicorp-21.7.1
      pullSecret: regcred
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: quorumstalv
      role: vault-role
      serviceaccountname: vault-auth
      keyprefix: stalv-quo/crypto
      tmprefix: secretsv2/data/stalv-quo/crypto
